
export const plantList = [
    {
        name: "Monstera",
        category: "Classic",
        id: "1m",
        price: 25.00,
        rating: 4.4,
        reviewCount: 325,
        currency: "GHS",
        bestSale: true,
        light: 2,
        water: 3,
        cover: '/images/monstera.jpg'
    },
    {
        name: "Ficus Lyrata",
        catregory: "Classic",
        id: "2f",
        price: 26.50,
        rating: 4.8,
        reviewCount: 355,
        currency: "GHS",
        light: 3,
        water: 2,
        cover: '/images/lyrata.jpg'
         
    },
    {
        name: "Silver Pothos",
        category: "Classic",
        id: "3s",
        price: 23.00,
        rating: 3.5,
        reviewCount: 450,
        currency: "GHS",
        light: 1,
        water: 2,
        cover: '/images/pothos.jpg'
    },
    {
        name: "Yucca",
        category: "Classic",
        id: "4y",
        price: 28.00,
        rating: 4.5,
        reviewCount: 650,
        currency: "GHS",
        light: 3,
        water: 1,
        cover: '/images/yucca.jpg'
    },
    {
        name: "Palm",
        category: "Exterior",
        id: "5p",
        price: 40.00,
        rating: 4.0,
        reviewCount: 750,
        currency: "GHS",
        light: 3,
        water: 2,
        cover: '/images/palm.jpg'
    },
    {
        name: "Olive Tree",
        category: "Exterior",
        id: "6o",
        price: 32.50,
        rating: 3.5,
        reviewCount: 550,
        currency: "GHS",
        bestSale: false,
        light: 3,
        water: 2,
        cover: '/images/olive.jpg'
    },
    {
        name: "Geranium",
        category: "Exterior",
        id: "7g",
        price: 27.60,
        rating: 3.9,
        reviewCount: 500,
        currency: "GHS",
        light: 3,
        water: 2,
        cover: '/images/geranium.jpg'
    },
    {
        name: "Basil",
        category: "Exterior",
        id: "8b",
        price: 25.00,
        rating: 5.0,
        reviewCount: 850,
        currency: "GHS",
        bestSale: true,
        light: 3,
        water: 3,
        cover: '/images/basil.jpg'
    },
    {
        name: "Mint",
        category: "Succulent",
        id: "9a",
        price: 45.00,
        rating: 3.7,
        reviewCount: 499,
        currency: "GHS",
        bestSale: true,
        light: 2,
        water: 1,
        cover: '/images/mint.jpg'
    },
    {
        name: "Succulent",
        category: "Succulent",
        id: "10s",
        price: 26.50,
        rating: 4.5,
        reviewCount: 750,
        currency: "GHS",
        light: 2,
        water: 1,
        cover: '/images/succulent.jpg'
    },
    {
        name: "Calathea",
        category: "Succulent",
        id: "11s",
        price: 26.50,
        rating: 4.2,
        reviewCount: 680,
        currency: "GHS",
        light: 2,
        water: 1,
        cover: '/images/calathea.jpg'
    }
];